### ISSUE TITLE
Slackbot responses

### ISSUE THREAD

**Issue by mattiaz** [mattiaz/slack-text2speech#6]
The nice delay between all messages sometimes disappears, meaning two messages is played at the same time. Long messages and slackbot responses seem to caus the bug. More info is needed

**Comment by mattiaz** [comment]
Multiple messages on short interval seem to cause the messages overlapping and being read at the same time. Can crash low end machines and or cause this error.

![error](https://cloud.githubusercontent.com/assets/4354701/20388951/834fa436-acc7-11e6-95c1-5c135e7d8ecf.png)

**Comment by Taluunas** [comment]
Go through msg text and skip repeating symbols. Perhaps >5

**Comment by mattiaz** [comment]
This project will soon be archived. Closing all issues.
